from app.tools.security import check_address_risk
from app.tools.scoring import calculate_score
from app.wallet import get_wallet_data
from app.risk_engine import calculate_risk_engine
from app.decision_agent import make_final_decision



def analyze(address):


    wallet_data = get_wallet_data(address)



    security = check_address_risk(
        address,
        wallet_data
    )



    result = calculate_score(
        wallet_data
    )



    result["wallet_metrics"] = wallet_data


    result["security"] = security



    #
    # Risk Fusion
    #

    result["risk_engine"] = calculate_risk_engine(
        wallet_data,
        result,
        security
    )



    #
    # Risk Engine becomes source of truth
    #

    result["risk_level"] = (
        result["risk_engine"]["risk_level"]
    )


    result["trust_score"] = (
        result["risk_engine"]["risk_score"]
    )



    #
    # Unified Explainable Signals
    #

    result["signals"] = (

        result["risk_engine"]["signals"]["positive"]

        +

        result["risk_engine"]["signals"]["negative"]

        +

        result["risk_engine"]["signals"]["unknown"]

    )



    result["explanation"] = {


        "positive":

            result["risk_engine"]["signals"]["positive"],


        "negative":

            result["risk_engine"]["signals"]["negative"],


        "unknown":

            result["risk_engine"]["signals"]["unknown"]

    }



    #
    # Final Decision Agent
    #

    result["final_decision"] = make_final_decision(
        wallet_data,
        result["risk_engine"],
        security
    )



    #
    # Recommendation
    #

    if result["risk_level"] == "LOW":

        result["recommendation"] = (
            "Low risk wallet. Interaction allowed."
        )


    elif result["risk_level"] == "MEDIUM":

        result["recommendation"] = (
            "Proceed with caution. Review wallet activity."
        )


    else:

        result["recommendation"] = (
            "Avoid interaction until wallet is reviewed."
        )



    #
    # Compatibility Agent Decision
    #

    result["agent_decision"] = {


        "decision":

            result["final_decision"]["final_decision"],


        "confidence":

            result["final_decision"]["confidence"],


        "data_quality_confidence":

            wallet_data["data_quality"]["confidence"],


        "reasoning":

            result["final_decision"]["reasoning"],


        "recommended_action":

            result["final_decision"]["recommended_action"],


        "limitations":

            wallet_data["data_quality"]["warnings"]

    }



    #
    # Reasoning Agent output
    #

    result["reasoning_agent"] = {

        "agent":

            "Decision Agent",


        "thought":

            "Final decision generated by Risk Fusion and Decision Intelligence layers.",


        "action":

            result["final_decision"]["final_decision"]

    }



    return result
